twig:
  file_name_pattern: "*.twig"
  date:
    format: d/m/Y
  globals:
    chemin_images: "/images/"
    chemin_docs: "/docs/"
    chemin_uploads: "/uploads/"

when@test:
  twig:
    strict_variables: true
